version: "3"
services:
  app:
    image: app:2.0.9 #change to latest when deploying on EC2
    depends_on:
      - mongodb
    ports:
      - 5001:5001
    networks:
            appnet:
                ipv4_address: 172.24.2.1
    # environment:
    #   - API_key="$API_KEY" # activate SSM Parameter store fucntion when deploying on EC2
  
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
            appnet:
                ipv4_address: 172.24.2.2
networks:
    appnet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.24.2.0/16"
